language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

sudo: required

os:
  - linux
  - osx

language: go

go:
  - 1.5.1
  - tip

env:
  - APM_TEST_PACKAGES="environment"

script: './build-package.sh'

git:
  depth: 10
