language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

sudo: required

os:
  - linux
  - osx

language: go

go:
  - 1.5.1
  - tip

before_script:
  - pushd $HOME
  - mkdir -p go
  - export GOPATH="$HOME/go"
  - export PATH=$PATH:$GOPATH/bin
  - go version
  - go env
  - popd

env:
  - APM_TEST_PACKAGES="environment"

script: './build-package.sh'

git:
  depth: 10
