notifications:
  email:
    on_success: never
    on_failure: change

os:
  - linux

language: go

go:
  - 1.5.1

env:
  global:
    - APM_TEST_PACKAGES="environment"

  matrix:
    - ATOM_CHANNEL=beta

script:
  - ./build-package.sh

git:
  depth: 10

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - gdebi-core
